In [ ]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM irrigated_land_data", staging_engine)
df=df.drop('Note',axis=1)
df.drop_duplicates()
df.info()
newest_years=df[df['Year']>=2000]
newest_years.sort_values(by='Year')
newest_years.info()
newest_years
newest_years.to_csv('F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\irrigated_land_edited.csv')
df.to_sql("clean_irrigated_land", cleaning_engine, if_exists="replace", index=False)
print("Data cleaned and loaded into cleaning_db successfully.")

<class 'pandas.core.frame.DataFrame'>
Index: 9038 entries, 111 to 22614
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ï»¿Domain Code    9038 non-null   object
 1   Domain            9038 non-null   object
 2   Area Code (M49)   9038 non-null   int64
 3   Area              9038 non-null   object
 4   Element Code      9038 non-null   int64
 5   Element           9038 non-null   object
 6   Item Code         9038 non-null   object
 7   Item              9038 non-null   object
 8   Year Code         9038 non-null   int64
 9   Year              9038 non-null   int64
 10  Unit              9038 non-null   object
 11  Value             9014 non-null   float64
 12  Flag              9038 non-null   object
 13  Flag Description  9038 non-null   object
 14  Note              273 non-null    object
dtypes: float64(1), int64(4), object(10)
memory usage: 1.1+ MB

,ï»¿Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
111,QCL,Crops and livestock products,818,Egypt,5312,Area harvested,111,Wheat,2000,2000,ha,1034985.00,A,Official figure,None
112,QCL,Crops and livestock products,818,Egypt,5412,Yield,111,Wheat,2000,2000,kg/ha,6342.20,A,Official figure,None
113,QCL,Crops and livestock products,818,Egypt,5510,Production,111,Wheat,2000,2000,t,6564053.00,A,Official figure,None
114,QCL,Crops and livestock products,818,Egypt,5312,Area harvested,111,Wheat,2001,2001,ha,983741.00,A,Official figure,None
115,QCL,Crops and livestock products,818,Egypt,5412,Yield,111,Wheat,2001,2001,kg/ha,6358.00,A,Official figure,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22610,QCL,Crops and livestock products,818,Egypt,5412,Yield,1221,Watermelons,2023,2023,kg/ha,33459.70,A,Official figure,None
22611,QCL,Crops and livestock products,818,Egypt,5510,Production,1221,Watermelons,2023,2023,t,695661.00,A,Official figure,None
22612,QCL,Crops and livestock products,818,Egypt,5312,Area harvested,1221,Watermelons,2024,2024,ha,21455.00,I,Value imputed by a receiving agency,None
22613,QCL,Crops and livestock products,818,Egypt,5412,Yield,1221,Watermelons,2024,2024,kg/ha,33208.90,E,Estimated value,None
22614,QCL,Crops and livestock products,818,Egypt,5510,Production,1221,Watermelons,2024,2024,t,712514.04,I,Value imputed by a receiving agency,None

In [82]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM rainful_Temperature_data", staging_engine)
# df=df.isnull().sum()
# df.drop_duplicates()
# df.info()

unpivoted_df = pd.melt(df, id_vars=['PARAMETER', 'YEAR', 'LAT', 'LON'], var_name='MONTH', value_name='TEMPERATURE')
newest_years=unpivoted_df[unpivoted_df['YEAR']>=2000]
newest_years.sort_values(by='YEAR')
newest_years.info()
newest_years
# newest_years.to_csv(r'F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\rainfull_temperature_edited.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172900 entries, 0 to 172899
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   PARAMETER    172900 non-null  object
 1   YEAR         172900 non-null  int64
 2   LAT          172900 non-null  float64
 3   LON          172900 non-null  float64
 4   MONTH        172900 non-null  object
 5   TEMPERATURE  172900 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 7.9+ MB

       PARAMETER  YEAR   LAT     LON MONTH  TEMPERATURE
0            T2M  2019  25.5  29.375   JAN        10.48
1            T2M  2019  25.5  30.000   JAN        10.72
2            T2M  2019  25.5  30.625   JAN        11.71
3            T2M  2019  25.5  31.250   JAN        10.31
4            T2M  2019  25.5  31.875   JAN        10.90
...          ...   ...   ...     ...   ...          ...
172895       T2M  2019  25.5  26.250   ANN        21.28
172896       T2M  2019  25.5  26.875   ANN        21.46
172897       T2M  2019  25.5  27.500   ANN        21.93
172898       T2M  2019  25.5  28.125   ANN        22.86
172899       T2M  2019  25.5  28.750   ANN        23.20

[172900 rows x 6 columns]

In [ ]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM arable_land_data", staging_engine)
df=df.isnull().sum()
df.drop_duplicates()
df.info()
df
unpivoted_df = pd.melt(df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], var_name='YEAR', value_name='VALUE')
unpivoted_df
newest_years=unpivoted_df[unpivoted_df['YEAR']>='2000']
newest_years.sort_values(by='YEAR')
newest_years.info()
newest_years=newest_years.dropna(subset=['YEAR','VALUE'])
newest_years.info()
newest_years
# newest_years.to_csv(r'F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\arable_land_data_edited.csv')

<class 'pandas.core.frame.DataFrame'>
Index: 6012 entries, 10640 to 17023
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    6012 non-null   object
 1   Country Code    6012 non-null   object
 2   Indicator Name  6012 non-null   object
 3   Indicator Code  6012 non-null   object
 4   YEAR            6012 non-null   object
 5   VALUE           6012 non-null   object
dtypes: object(6)
memory usage: 328.8+ KB

,Country Name,Country Code,Indicator Name,Indicator Code,YEAR,VALUE
10640,Aruba,ABW,Arable land (% of land area),AG.LND.ARBL.ZS,2000,11.111111
10641,Africa Eastern and Southern,AFE,Arable land (% of land area),AG.LND.ARBL.ZS,2000,6.040619
10642,Afghanistan,AFG,Arable land (% of land area),AG.LND.ARBL.ZS,2000,11.779587
10643,Africa Western and Central,AFW,Arable land (% of land area),AG.LND.ARBL.ZS,2000,9.958886
10644,Angola,AGO,Arable land (% of land area),AG.LND.ARBL.ZS,2000,2.406353
...,...,...,...,...,...,...
17018,Samoa,WSM,Arable land (% of land area),AG.LND.ARBL.ZS,2023,3.852518
17020,"Yemen, Rep.",YEM,Arable land (% of land area),AG.LND.ARBL.ZS,2023,2.193306
17021,South Africa,ZAF,Arable land (% of land area),AG.LND.ARBL.ZS,2023,9.892094
17022,Zambia,ZMB,Arable land (% of land area),AG.LND.ARBL.ZS,2023,5.111718
17023,Zimbabwe,ZWE,Arable land (% of land area),AG.LND.ARBL.ZS,2023,10.392679

In [79]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM co2_emmisions_data", staging_engine)
df
# df=df.isnull().sum()
df.drop_duplicates()
# df.info()
# df

unpivoted_df = pd.melt(df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], var_name='YEAR', value_name='VALUE')
unpivoted_df
newest_years=unpivoted_df[unpivoted_df['YEAR']>='2000']
newest_years.sort_values(by='YEAR')

newest_years=newest_years.dropna(subset=['YEAR','VALUE'])
newest_years.info()
newest_years
# newest_years.to_csv(r'F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\co2_emmisions_data_edited.csv')

<class 'pandas.core.frame.DataFrame'>
Index: 3900 entries, 10641 to 17289
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    3900 non-null   object
 1   Country Code    3900 non-null   object
 2   Indicator Name  3900 non-null   object
 3   Indicator Code  3900 non-null   object
 4   YEAR            3900 non-null   object
 5   VALUE           3900 non-null   object
dtypes: object(6)
memory usage: 213.3+ KB

,Country Name,Country Code,Indicator Name,Indicator Code,YEAR,VALUE
10641,Africa Eastern and Southern,AFE,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2000,0.8608
10642,Afghanistan,AFG,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2000,0.0079
10643,Africa Western and Central,AFW,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2000,0.2423
10645,Albania,ALB,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2000,0.0166
10647,Arab World,ARB,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2000,4.7746
...,...,...,...,...,...,...
17281,Viet Nam,VNM,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2024,2.1665
17283,World,WLD,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2024,143.473938
17287,South Africa,ZAF,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2024,1.2755
17288,Zambia,ZMB,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2024,0.2651
17289,Zimbabwe,ZWE,Carbon dioxide (CO2) emissions from Agricultur...,EN.GHG.CO2.AG.MT.CE.AR5,2024,0.0353

In [ ]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM fertilizer_use_data", staging_engine)
# df=df.isnull().sum()
# df.drop_duplicates()
# df.info()
# df

unpivoted_df = pd.melt(df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], var_name='YEAR', value_name='VALUE')
# unpivoted_df
newest_years=unpivoted_df[unpivoted_df['YEAR']>='2000']
newest_years.sort_values(by='YEAR')

newest_years=newest_years[~(newest_years['YEAR'].astype(str).str.contains("Unnamed")) & ~(newest_years['YEAR'].astype(str).str.contains("2024"))]
newest_years['VALUE']=newest_years['VALUE'].fillna(method="ffill").fillna(method="bfill")
# newest_years=newest_years.dropna(subset=['YEAR'])
newest_years.info()
newest_years
# newest_years.to_csv(r'F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\fertilizer_use_data_edited.csv')

<class 'pandas.core.frame.DataFrame'>
Index: 6384 entries, 10640 to 17023
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    6384 non-null   object
 1   Country Code    6384 non-null   object
 2   Indicator Name  6384 non-null   object
 3   Indicator Code  6384 non-null   object
 4   YEAR            6384 non-null   object
 5   VALUE           6384 non-null   float64
dtypes: float64(1), object(5)
memory usage: 349.1+ KB

C:\Users\DELL\AppData\Local\Temp\ipykernel_2908\3775975392.py:39: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newest_years['VALUE']=newest_years['VALUE'].fillna(method="ffill").fillna(method="bfill")
C:\Users\DELL\AppData\Local\Temp\ipykernel_2908\3775975392.py:39: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  newest_years['VALUE']=newest_years['VALUE'].fillna(method="ffill").fillna(method="bfill")

,Country Name,Country Code,Indicator Name,Indicator Code,YEAR,VALUE
10640,Aruba,ABW,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2000,19.227512
10641,Africa Eastern and Southern,AFE,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2000,19.227512
10642,Afghanistan,AFG,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2000,0.650787
10643,Africa Western and Central,AFW,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2000,5.763464
10644,Angola,AGO,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2000,0.466667
...,...,...,...,...,...,...
17019,Kosovo,XKX,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2023,1.027077
17020,"Yemen, Rep.",YEM,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2023,8.930052
17021,South Africa,ZAF,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2023,77.186583
17022,Zambia,ZMB,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2023,77.271053
17023,Zimbabwe,ZWE,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,2023,26.213262

In [77]:
# transformations/clean_fakestore_products.py
import pandas as pd
from sqlalchemy import create_engine
import re

server = "localhost"
database = "agr_staging_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
staging_engine = create_engine(connection_string)

server = "localhost"
database = "agr_cleaning_db"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
cleaning_engine = create_engine(connection_string)

# Read from staging table
df = pd.read_sql("SELECT * FROM population_data", staging_engine)

# df=df.isnull().sum()
df.drop_duplicates()
# df.info()
# df

unpivoted_df = pd.melt(df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], var_name='YEAR', value_name='VALUE')
unpivoted_df
newest_years=unpivoted_df[unpivoted_df['YEAR']>='2000']
newest_years.sort_values(by='YEAR')

newest_years=newest_years.dropna(subset=['YEAR','VALUE'])
newest_years.info()
newest_years
newest_years.to_csv(r'F:\رواد مصر تراك تحليل البيانات\Tasks & Practices\Agriculture project\population_data_edited.csv')

<class 'pandas.core.frame.DataFrame'>
Index: 6625 entries, 10640 to 17289
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    6625 non-null   object
 1   Country Code    6625 non-null   object
 2   Indicator Name  6625 non-null   object
 3   Indicator Code  6625 non-null   object
 4   YEAR            6625 non-null   object
 5   VALUE           6625 non-null   object
dtypes: object(6)
memory usage: 362.3+ KB